name: go

on:
  push:
    branches: [ main ]
jobs:
  build-lin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - name: Build-lin
      run: go build -x -v 
    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: Linux
        path: ./weather-Cli

  build-win: 
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - name: Build-win
      run: go build -x -v 
    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: Windows
        path: ./weather-Cli.exe


  build-mac:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - name: Build-mac
      run: go build -x -v 
    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: MacOS
        path: ./weather-Cli

